version: "3.9"

services:
  web:
    build: .
    container_name: ml-flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python app.py
